/*
 * generated by Xtext 2.27.0
 */
package fr.centralesupelec.infonum.sl.miniarm.validation;

import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.validation.CheckType;

import fr.centralesupelec.infonum.sl.miniarm.miniARM.Include;
//import fr.centralesupelec.infonum.sl.miniarm.miniARM.MiniARMPackage;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class MiniARMValidator extends AbstractMiniARMValidator {
	@Check(CheckType.FAST)
	public Resource checkIncludeFileExists(Include inc) {
		Resource progres = inc.eContainer().eResource();
		ResourceSet rset = progres.getResourceSet();
		Resource incres = null;
		try {
			incres = rset.getResource(progres.getURI().trimSegments(1).appendSegment(inc.getFileName()), true);
		} catch (Exception exc) {
			// incres will be null if there is an exception
			// The following code causes an error because ThreadLocal.get() returns null in AbstractDeclarativeValidator.error
//			error("Included file \"" + inc.getFileName() + "\" does not exist",
//					MiniARMPackage.Literals.INCLUDE__FILE_NAME); // no such file
			
			System.err.println("Included file \"" + inc.getFileName() + "\" does not exist");
		}
		return incres;
	}

//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					MiniARMPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
}
