/*
 * generated by Xtext 2.27.0
 */
package fr.centralesupelec.infonum.sl.miniarm.parser.antlr;

import com.google.inject.Inject;
import fr.centralesupelec.infonum.sl.miniarm.parser.antlr.internal.InternalMiniARMParser;
import fr.centralesupelec.infonum.sl.miniarm.services.MiniARMGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MiniARMParser extends AbstractAntlrParser {

	@Inject
	private MiniARMGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS");
	}
	

	@Override
	protected InternalMiniARMParser createParser(XtextTokenStream stream) {
		return new InternalMiniARMParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public MiniARMGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MiniARMGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
