/*
 * generated by Xtext 2.27.0
 */
package fr.centralesupelec.infonum.sl.miniarm.ui;

import com.google.inject.Injector;
import fr.centralesupelec.infonum.sl.miniarm.ui.internal.MiniarmActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MiniARMExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MiniarmActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MiniarmActivator activator = MiniarmActivator.getInstance();
		return activator != null ? activator.getInjector(MiniarmActivator.FR_CENTRALESUPELEC_INFONUM_SL_MINIARM_MINIARM) : null;
	}

}
