/**
 * generated by Xtext 2.27.0
 */
package fr.centralesupelec.infonum.sl.miniarm.miniARM;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assembly Inst</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.MiniARMPackage#getAssemblyInst()
 * @model
 * @generated
 */
public interface AssemblyInst extends Instruction
{
} // AssemblyInst
