/**
 * generated by Xtext 2.27.0
 */
package fr.centralesupelec.infonum.sl.miniarm.miniARM;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.MiniARMPackage
 * @generated
 */
public interface MiniARMFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MiniARMFactory eINSTANCE = fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Program</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Program</em>'.
   * @generated
   */
  Program createProgram();

  /**
   * Returns a new object of class '<em>Line</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Line</em>'.
   * @generated
   */
  Line createLine();

  /**
   * Returns a new object of class '<em>Include</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Include</em>'.
   * @generated
   */
  Include createInclude();

  /**
   * Returns a new object of class '<em>Label Def</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Label Def</em>'.
   * @generated
   */
  LabelDef createLabelDef();

  /**
   * Returns a new object of class '<em>Label</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Label</em>'.
   * @generated
   */
  Label createLabel();

  /**
   * Returns a new object of class '<em>Instruction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Instruction</em>'.
   * @generated
   */
  Instruction createInstruction();

  /**
   * Returns a new object of class '<em>Assembly Inst</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Assembly Inst</em>'.
   * @generated
   */
  AssemblyInst createAssemblyInst();

  /**
   * Returns a new object of class '<em>Pseudo Inst</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pseudo Inst</em>'.
   * @generated
   */
  PseudoInst createPseudoInst();

  /**
   * Returns a new object of class '<em>Real Inst</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Real Inst</em>'.
   * @generated
   */
  RealInst createRealInst();

  /**
   * Returns a new object of class '<em>RMW</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RMW</em>'.
   * @generated
   */
  RMW createRMW();

  /**
   * Returns a new object of class '<em>SMW</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SMW</em>'.
   * @generated
   */
  SMW createSMW();

  /**
   * Returns a new object of class '<em>SMS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SMS</em>'.
   * @generated
   */
  SMS createSMS();

  /**
   * Returns a new object of class '<em>PUSH</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PUSH</em>'.
   * @generated
   */
  PUSH createPUSH();

  /**
   * Returns a new object of class '<em>POP</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>POP</em>'.
   * @generated
   */
  POP createPOP();

  /**
   * Returns a new object of class '<em>LOAD</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>LOAD</em>'.
   * @generated
   */
  LOAD createLOAD();

  /**
   * Returns a new object of class '<em>Register</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Register</em>'.
   * @generated
   */
  Register createRegister();

  /**
   * Returns a new object of class '<em>Immediate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Immediate</em>'.
   * @generated
   */
  Immediate createImmediate();

  /**
   * Returns a new object of class '<em>Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Value</em>'.
   * @generated
   */
  Value createValue();

  /**
   * Returns a new object of class '<em>Const</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Const</em>'.
   * @generated
   */
  Const createConst();

  /**
   * Returns a new object of class '<em>Hex Const</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Hex Const</em>'.
   * @generated
   */
  HexConst createHexConst();

  /**
   * Returns a new object of class '<em>Direct</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Direct</em>'.
   * @generated
   */
  Direct createDirect();

  /**
   * Returns a new object of class '<em>Direct Reg</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Direct Reg</em>'.
   * @generated
   */
  DirectReg createDirectReg();

  /**
   * Returns a new object of class '<em>STORE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>STORE</em>'.
   * @generated
   */
  STORE createSTORE();

  /**
   * Returns a new object of class '<em>Address</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Address</em>'.
   * @generated
   */
  Address createAddress();

  /**
   * Returns a new object of class '<em>MOVE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MOVE</em>'.
   * @generated
   */
  MOVE createMOVE();

  /**
   * Returns a new object of class '<em>Move Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Move Value</em>'.
   * @generated
   */
  MoveValue createMoveValue();

  /**
   * Returns a new object of class '<em>ADD</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ADD</em>'.
   * @generated
   */
  ADD createADD();

  /**
   * Returns a new object of class '<em>SUB</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SUB</em>'.
   * @generated
   */
  SUB createSUB();

  /**
   * Returns a new object of class '<em>CMP</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CMP</em>'.
   * @generated
   */
  CMP createCMP();

  /**
   * Returns a new object of class '<em>BEQ</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>BEQ</em>'.
   * @generated
   */
  BEQ createBEQ();

  /**
   * Returns a new object of class '<em>Branch Address</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Branch Address</em>'.
   * @generated
   */
  BranchAddress createBranchAddress();

  /**
   * Returns a new object of class '<em>BLT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>BLT</em>'.
   * @generated
   */
  BLT createBLT();

  /**
   * Returns a new object of class '<em>BRANCH</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>BRANCH</em>'.
   * @generated
   */
  BRANCH createBRANCH();

  /**
   * Returns a new object of class '<em>BLINK</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>BLINK</em>'.
   * @generated
   */
  BLINK createBLINK();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MiniARMPackage getMiniARMPackage();

} //MiniARMFactory
