/**
 * generated by Xtext 2.27.0
 */
package fr.centralesupelec.infonum.sl.miniarm.miniARM;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.MiniARMFactory
 * @model kind="package"
 * @generated
 */
public interface MiniARMPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "miniARM";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.centralesupelec.fr/infonum/sl/miniarm/MiniARM";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "miniARM";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MiniARMPackage eINSTANCE = fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.ProgramImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Lines</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__LINES = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.LineImpl <em>Line</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.LineImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getLine()
   * @generated
   */
  int LINE = 1;

  /**
   * The feature id for the '<em><b>Label Def</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE__LABEL_DEF = 0;

  /**
   * The feature id for the '<em><b>Inst</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE__INST = 1;

  /**
   * The feature id for the '<em><b>Comment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE__COMMENT = 2;

  /**
   * The number of structural features of the '<em>Line</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.IncludeImpl <em>Include</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.IncludeImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getInclude()
   * @generated
   */
  int INCLUDE = 2;

  /**
   * The feature id for the '<em><b>Label Def</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCLUDE__LABEL_DEF = LINE__LABEL_DEF;

  /**
   * The feature id for the '<em><b>Inst</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCLUDE__INST = LINE__INST;

  /**
   * The feature id for the '<em><b>Comment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCLUDE__COMMENT = LINE__COMMENT;

  /**
   * The feature id for the '<em><b>File Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCLUDE__FILE_NAME = LINE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Include</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCLUDE_FEATURE_COUNT = LINE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.LabelDefImpl <em>Label Def</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.LabelDefImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getLabelDef()
   * @generated
   */
  int LABEL_DEF = 3;

  /**
   * The feature id for the '<em><b>Label</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_DEF__LABEL = 0;

  /**
   * The number of structural features of the '<em>Label Def</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_DEF_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.LabelImpl <em>Label</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.LabelImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getLabel()
   * @generated
   */
  int LABEL = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL__NAME = 0;

  /**
   * The number of structural features of the '<em>Label</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.InstructionImpl <em>Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.InstructionImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getInstruction()
   * @generated
   */
  int INSTRUCTION = 5;

  /**
   * The number of structural features of the '<em>Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.AssemblyInstImpl <em>Assembly Inst</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.AssemblyInstImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getAssemblyInst()
   * @generated
   */
  int ASSEMBLY_INST = 6;

  /**
   * The number of structural features of the '<em>Assembly Inst</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSEMBLY_INST_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.PseudoInstImpl <em>Pseudo Inst</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.PseudoInstImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getPseudoInst()
   * @generated
   */
  int PSEUDO_INST = 7;

  /**
   * The feature id for the '<em><b>Reg</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PSEUDO_INST__REG = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Pseudo Inst</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PSEUDO_INST_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.RealInstImpl <em>Real Inst</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.RealInstImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getRealInst()
   * @generated
   */
  int REAL_INST = 8;

  /**
   * The number of structural features of the '<em>Real Inst</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REAL_INST_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.RMWImpl <em>RMW</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.RMWImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getRMW()
   * @generated
   */
  int RMW = 9;

  /**
   * The feature id for the '<em><b>Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RMW__SIZE = ASSEMBLY_INST_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>RMW</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RMW_FEATURE_COUNT = ASSEMBLY_INST_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.SMWImpl <em>SMW</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.SMWImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getSMW()
   * @generated
   */
  int SMW = 10;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMW__VALUE = ASSEMBLY_INST_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>SMW</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMW_FEATURE_COUNT = ASSEMBLY_INST_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.SMSImpl <em>SMS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.SMSImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getSMS()
   * @generated
   */
  int SMS = 11;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMS__VALUE = ASSEMBLY_INST_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>SMS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMS_FEATURE_COUNT = ASSEMBLY_INST_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.PUSHImpl <em>PUSH</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.PUSHImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getPUSH()
   * @generated
   */
  int PUSH = 12;

  /**
   * The feature id for the '<em><b>Reg</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUSH__REG = PSEUDO_INST__REG;

  /**
   * The number of structural features of the '<em>PUSH</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUSH_FEATURE_COUNT = PSEUDO_INST_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.POPImpl <em>POP</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.POPImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getPOP()
   * @generated
   */
  int POP = 13;

  /**
   * The feature id for the '<em><b>Reg</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POP__REG = PSEUDO_INST__REG;

  /**
   * The number of structural features of the '<em>POP</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POP_FEATURE_COUNT = PSEUDO_INST_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.LOADImpl <em>LOAD</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.LOADImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getLOAD()
   * @generated
   */
  int LOAD = 14;

  /**
   * The feature id for the '<em><b>Reg</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD__REG = REAL_INST_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Address</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD__ADDRESS = REAL_INST_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>LOAD</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_FEATURE_COUNT = REAL_INST_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MoveValueImpl <em>Move Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MoveValueImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getMoveValue()
   * @generated
   */
  int MOVE_VALUE = 25;

  /**
   * The number of structural features of the '<em>Move Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_VALUE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.RegisterImpl <em>Register</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.RegisterImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getRegister()
   * @generated
   */
  int REGISTER = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGISTER__NAME = MOVE_VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Register</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGISTER_FEATURE_COUNT = MOVE_VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.ImmediateImpl <em>Immediate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.ImmediateImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getImmediate()
   * @generated
   */
  int IMMEDIATE = 16;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMMEDIATE__VALUE = MOVE_VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Immediate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMMEDIATE_FEATURE_COUNT = MOVE_VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.BranchAddressImpl <em>Branch Address</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.BranchAddressImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getBranchAddress()
   * @generated
   */
  int BRANCH_ADDRESS = 30;

  /**
   * The number of structural features of the '<em>Branch Address</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BRANCH_ADDRESS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.ValueImpl <em>Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.ValueImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getValue()
   * @generated
   */
  int VALUE = 17;

  /**
   * The feature id for the '<em><b>Label</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__LABEL = BRANCH_ADDRESS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__NUM = BRANCH_ADDRESS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_FEATURE_COUNT = BRANCH_ADDRESS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.ConstImpl <em>Const</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.ConstImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getConst()
   * @generated
   */
  int CONST = 18;

  /**
   * The feature id for the '<em><b>Label</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONST__LABEL = VALUE__LABEL;

  /**
   * The feature id for the '<em><b>Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONST__NUM = VALUE__NUM;

  /**
   * The number of structural features of the '<em>Const</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONST_FEATURE_COUNT = VALUE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.HexConstImpl <em>Hex Const</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.HexConstImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getHexConst()
   * @generated
   */
  int HEX_CONST = 19;

  /**
   * The feature id for the '<em><b>Label</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEX_CONST__LABEL = VALUE__LABEL;

  /**
   * The feature id for the '<em><b>Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEX_CONST__NUM = VALUE__NUM;

  /**
   * The number of structural features of the '<em>Hex Const</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEX_CONST_FEATURE_COUNT = VALUE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.AddressImpl <em>Address</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.AddressImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getAddress()
   * @generated
   */
  int ADDRESS = 23;

  /**
   * The number of structural features of the '<em>Address</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDRESS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.DirectImpl <em>Direct</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.DirectImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getDirect()
   * @generated
   */
  int DIRECT = 20;

  /**
   * The feature id for the '<em><b>Address</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECT__ADDRESS = ADDRESS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Direct</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECT_FEATURE_COUNT = ADDRESS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.DirectRegImpl <em>Direct Reg</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.DirectRegImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getDirectReg()
   * @generated
   */
  int DIRECT_REG = 21;

  /**
   * The feature id for the '<em><b>Reg</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECT_REG__REG = ADDRESS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Direct Reg</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECT_REG_FEATURE_COUNT = ADDRESS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.STOREImpl <em>STORE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.STOREImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getSTORE()
   * @generated
   */
  int STORE = 22;

  /**
   * The feature id for the '<em><b>Reg</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE__REG = REAL_INST_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Address</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE__ADDRESS = REAL_INST_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>STORE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_FEATURE_COUNT = REAL_INST_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MOVEImpl <em>MOVE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MOVEImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getMOVE()
   * @generated
   */
  int MOVE = 24;

  /**
   * The feature id for the '<em><b>Dst</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__DST = REAL_INST_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Src</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__SRC = REAL_INST_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>MOVE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_FEATURE_COUNT = REAL_INST_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.ADDImpl <em>ADD</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.ADDImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getADD()
   * @generated
   */
  int ADD = 26;

  /**
   * The feature id for the '<em><b>Dst</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD__DST = REAL_INST_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Src1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD__SRC1 = REAL_INST_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Src2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD__SRC2 = REAL_INST_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>ADD</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_FEATURE_COUNT = REAL_INST_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.SUBImpl <em>SUB</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.SUBImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getSUB()
   * @generated
   */
  int SUB = 27;

  /**
   * The feature id for the '<em><b>Dst</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB__DST = REAL_INST_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Src1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB__SRC1 = REAL_INST_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Src2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB__SRC2 = REAL_INST_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>SUB</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_FEATURE_COUNT = REAL_INST_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.CMPImpl <em>CMP</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.CMPImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getCMP()
   * @generated
   */
  int CMP = 28;

  /**
   * The feature id for the '<em><b>Src1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMP__SRC1 = REAL_INST_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Src2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMP__SRC2 = REAL_INST_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>CMP</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CMP_FEATURE_COUNT = REAL_INST_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.BEQImpl <em>BEQ</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.BEQImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getBEQ()
   * @generated
   */
  int BEQ = 29;

  /**
   * The feature id for the '<em><b>Dest</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEQ__DEST = REAL_INST_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>BEQ</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEQ_FEATURE_COUNT = REAL_INST_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.BLTImpl <em>BLT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.BLTImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getBLT()
   * @generated
   */
  int BLT = 31;

  /**
   * The feature id for the '<em><b>Dest</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLT__DEST = REAL_INST_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>BLT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLT_FEATURE_COUNT = REAL_INST_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.BRANCHImpl <em>BRANCH</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.BRANCHImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getBRANCH()
   * @generated
   */
  int BRANCH = 32;

  /**
   * The feature id for the '<em><b>Dest</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BRANCH__DEST = REAL_INST_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>BRANCH</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BRANCH_FEATURE_COUNT = REAL_INST_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.BLINKImpl <em>BLINK</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.BLINKImpl
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getBLINK()
   * @generated
   */
  int BLINK = 33;

  /**
   * The feature id for the '<em><b>Reg</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLINK__REG = REAL_INST_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Dest</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLINK__DEST = REAL_INST_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>BLINK</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLINK_FEATURE_COUNT = REAL_INST_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference list '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.Program#getLines <em>Lines</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lines</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.Program#getLines()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Lines();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.Line <em>Line</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Line</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.Line
   * @generated
   */
  EClass getLine();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.Line#getLabelDef <em>Label Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Label Def</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.Line#getLabelDef()
   * @see #getLine()
   * @generated
   */
  EReference getLine_LabelDef();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.Line#getInst <em>Inst</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Inst</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.Line#getInst()
   * @see #getLine()
   * @generated
   */
  EReference getLine_Inst();

  /**
   * Returns the meta object for the attribute '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.Line#getComment <em>Comment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comment</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.Line#getComment()
   * @see #getLine()
   * @generated
   */
  EAttribute getLine_Comment();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.Include <em>Include</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Include</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.Include
   * @generated
   */
  EClass getInclude();

  /**
   * Returns the meta object for the attribute '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.Include#getFileName <em>File Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>File Name</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.Include#getFileName()
   * @see #getInclude()
   * @generated
   */
  EAttribute getInclude_FileName();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.LabelDef <em>Label Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Label Def</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.LabelDef
   * @generated
   */
  EClass getLabelDef();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.LabelDef#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Label</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.LabelDef#getLabel()
   * @see #getLabelDef()
   * @generated
   */
  EReference getLabelDef_Label();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.Label <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Label</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.Label
   * @generated
   */
  EClass getLabel();

  /**
   * Returns the meta object for the attribute '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.Label#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.Label#getName()
   * @see #getLabel()
   * @generated
   */
  EAttribute getLabel_Name();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.Instruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruction</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.Instruction
   * @generated
   */
  EClass getInstruction();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.AssemblyInst <em>Assembly Inst</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assembly Inst</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.AssemblyInst
   * @generated
   */
  EClass getAssemblyInst();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.PseudoInst <em>Pseudo Inst</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pseudo Inst</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.PseudoInst
   * @generated
   */
  EClass getPseudoInst();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.PseudoInst#getReg <em>Reg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Reg</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.PseudoInst#getReg()
   * @see #getPseudoInst()
   * @generated
   */
  EReference getPseudoInst_Reg();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.RealInst <em>Real Inst</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Real Inst</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.RealInst
   * @generated
   */
  EClass getRealInst();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.RMW <em>RMW</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RMW</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.RMW
   * @generated
   */
  EClass getRMW();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.RMW#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Size</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.RMW#getSize()
   * @see #getRMW()
   * @generated
   */
  EReference getRMW_Size();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.SMW <em>SMW</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SMW</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.SMW
   * @generated
   */
  EClass getSMW();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.SMW#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.SMW#getValue()
   * @see #getSMW()
   * @generated
   */
  EReference getSMW_Value();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.SMS <em>SMS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SMS</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.SMS
   * @generated
   */
  EClass getSMS();

  /**
   * Returns the meta object for the attribute '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.SMS#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.SMS#getValue()
   * @see #getSMS()
   * @generated
   */
  EAttribute getSMS_Value();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.PUSH <em>PUSH</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>PUSH</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.PUSH
   * @generated
   */
  EClass getPUSH();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.POP <em>POP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>POP</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.POP
   * @generated
   */
  EClass getPOP();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.LOAD <em>LOAD</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>LOAD</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.LOAD
   * @generated
   */
  EClass getLOAD();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.LOAD#getReg <em>Reg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Reg</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.LOAD#getReg()
   * @see #getLOAD()
   * @generated
   */
  EReference getLOAD_Reg();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.LOAD#getAddress <em>Address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Address</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.LOAD#getAddress()
   * @see #getLOAD()
   * @generated
   */
  EReference getLOAD_Address();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.Register <em>Register</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Register</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.Register
   * @generated
   */
  EClass getRegister();

  /**
   * Returns the meta object for the attribute '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.Register#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.Register#getName()
   * @see #getRegister()
   * @generated
   */
  EAttribute getRegister_Name();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.Immediate <em>Immediate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Immediate</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.Immediate
   * @generated
   */
  EClass getImmediate();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.Immediate#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.Immediate#getValue()
   * @see #getImmediate()
   * @generated
   */
  EReference getImmediate_Value();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.Value <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.Value
   * @generated
   */
  EClass getValue();

  /**
   * Returns the meta object for the reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.Value#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Label</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.Value#getLabel()
   * @see #getValue()
   * @generated
   */
  EReference getValue_Label();

  /**
   * Returns the meta object for the attribute '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.Value#getNum <em>Num</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Num</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.Value#getNum()
   * @see #getValue()
   * @generated
   */
  EAttribute getValue_Num();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.Const <em>Const</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Const</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.Const
   * @generated
   */
  EClass getConst();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.HexConst <em>Hex Const</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hex Const</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.HexConst
   * @generated
   */
  EClass getHexConst();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.Direct <em>Direct</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Direct</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.Direct
   * @generated
   */
  EClass getDirect();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.Direct#getAddress <em>Address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Address</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.Direct#getAddress()
   * @see #getDirect()
   * @generated
   */
  EReference getDirect_Address();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.DirectReg <em>Direct Reg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Direct Reg</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.DirectReg
   * @generated
   */
  EClass getDirectReg();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.DirectReg#getReg <em>Reg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Reg</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.DirectReg#getReg()
   * @see #getDirectReg()
   * @generated
   */
  EReference getDirectReg_Reg();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.STORE <em>STORE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>STORE</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.STORE
   * @generated
   */
  EClass getSTORE();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.STORE#getReg <em>Reg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Reg</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.STORE#getReg()
   * @see #getSTORE()
   * @generated
   */
  EReference getSTORE_Reg();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.STORE#getAddress <em>Address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Address</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.STORE#getAddress()
   * @see #getSTORE()
   * @generated
   */
  EReference getSTORE_Address();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.Address <em>Address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Address</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.Address
   * @generated
   */
  EClass getAddress();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.MOVE <em>MOVE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MOVE</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.MOVE
   * @generated
   */
  EClass getMOVE();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.MOVE#getDst <em>Dst</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Dst</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.MOVE#getDst()
   * @see #getMOVE()
   * @generated
   */
  EReference getMOVE_Dst();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.MOVE#getSrc <em>Src</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Src</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.MOVE#getSrc()
   * @see #getMOVE()
   * @generated
   */
  EReference getMOVE_Src();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.MoveValue <em>Move Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move Value</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.MoveValue
   * @generated
   */
  EClass getMoveValue();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.ADD <em>ADD</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ADD</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.ADD
   * @generated
   */
  EClass getADD();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.ADD#getDst <em>Dst</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Dst</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.ADD#getDst()
   * @see #getADD()
   * @generated
   */
  EReference getADD_Dst();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.ADD#getSrc1 <em>Src1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Src1</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.ADD#getSrc1()
   * @see #getADD()
   * @generated
   */
  EReference getADD_Src1();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.ADD#getSrc2 <em>Src2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Src2</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.ADD#getSrc2()
   * @see #getADD()
   * @generated
   */
  EReference getADD_Src2();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.SUB <em>SUB</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SUB</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.SUB
   * @generated
   */
  EClass getSUB();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.SUB#getDst <em>Dst</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Dst</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.SUB#getDst()
   * @see #getSUB()
   * @generated
   */
  EReference getSUB_Dst();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.SUB#getSrc1 <em>Src1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Src1</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.SUB#getSrc1()
   * @see #getSUB()
   * @generated
   */
  EReference getSUB_Src1();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.SUB#getSrc2 <em>Src2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Src2</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.SUB#getSrc2()
   * @see #getSUB()
   * @generated
   */
  EReference getSUB_Src2();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.CMP <em>CMP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CMP</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.CMP
   * @generated
   */
  EClass getCMP();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.CMP#getSrc1 <em>Src1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Src1</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.CMP#getSrc1()
   * @see #getCMP()
   * @generated
   */
  EReference getCMP_Src1();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.CMP#getSrc2 <em>Src2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Src2</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.CMP#getSrc2()
   * @see #getCMP()
   * @generated
   */
  EReference getCMP_Src2();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.BEQ <em>BEQ</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BEQ</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.BEQ
   * @generated
   */
  EClass getBEQ();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.BEQ#getDest <em>Dest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Dest</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.BEQ#getDest()
   * @see #getBEQ()
   * @generated
   */
  EReference getBEQ_Dest();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.BranchAddress <em>Branch Address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Branch Address</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.BranchAddress
   * @generated
   */
  EClass getBranchAddress();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.BLT <em>BLT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BLT</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.BLT
   * @generated
   */
  EClass getBLT();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.BLT#getDest <em>Dest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Dest</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.BLT#getDest()
   * @see #getBLT()
   * @generated
   */
  EReference getBLT_Dest();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.BRANCH <em>BRANCH</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BRANCH</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.BRANCH
   * @generated
   */
  EClass getBRANCH();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.BRANCH#getDest <em>Dest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Dest</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.BRANCH#getDest()
   * @see #getBRANCH()
   * @generated
   */
  EReference getBRANCH_Dest();

  /**
   * Returns the meta object for class '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.BLINK <em>BLINK</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BLINK</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.BLINK
   * @generated
   */
  EClass getBLINK();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.BLINK#getReg <em>Reg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Reg</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.BLINK#getReg()
   * @see #getBLINK()
   * @generated
   */
  EReference getBLINK_Reg();

  /**
   * Returns the meta object for the containment reference '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.BLINK#getDest <em>Dest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Dest</em>'.
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.BLINK#getDest()
   * @see #getBLINK()
   * @generated
   */
  EReference getBLINK_Dest();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MiniARMFactory getMiniARMFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.ProgramImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Lines</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__LINES = eINSTANCE.getProgram_Lines();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.LineImpl <em>Line</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.LineImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getLine()
     * @generated
     */
    EClass LINE = eINSTANCE.getLine();

    /**
     * The meta object literal for the '<em><b>Label Def</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LINE__LABEL_DEF = eINSTANCE.getLine_LabelDef();

    /**
     * The meta object literal for the '<em><b>Inst</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LINE__INST = eINSTANCE.getLine_Inst();

    /**
     * The meta object literal for the '<em><b>Comment</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINE__COMMENT = eINSTANCE.getLine_Comment();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.IncludeImpl <em>Include</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.IncludeImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getInclude()
     * @generated
     */
    EClass INCLUDE = eINSTANCE.getInclude();

    /**
     * The meta object literal for the '<em><b>File Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INCLUDE__FILE_NAME = eINSTANCE.getInclude_FileName();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.LabelDefImpl <em>Label Def</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.LabelDefImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getLabelDef()
     * @generated
     */
    EClass LABEL_DEF = eINSTANCE.getLabelDef();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LABEL_DEF__LABEL = eINSTANCE.getLabelDef_Label();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.LabelImpl <em>Label</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.LabelImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getLabel()
     * @generated
     */
    EClass LABEL = eINSTANCE.getLabel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LABEL__NAME = eINSTANCE.getLabel_Name();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.InstructionImpl <em>Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.InstructionImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getInstruction()
     * @generated
     */
    EClass INSTRUCTION = eINSTANCE.getInstruction();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.AssemblyInstImpl <em>Assembly Inst</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.AssemblyInstImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getAssemblyInst()
     * @generated
     */
    EClass ASSEMBLY_INST = eINSTANCE.getAssemblyInst();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.PseudoInstImpl <em>Pseudo Inst</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.PseudoInstImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getPseudoInst()
     * @generated
     */
    EClass PSEUDO_INST = eINSTANCE.getPseudoInst();

    /**
     * The meta object literal for the '<em><b>Reg</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PSEUDO_INST__REG = eINSTANCE.getPseudoInst_Reg();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.RealInstImpl <em>Real Inst</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.RealInstImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getRealInst()
     * @generated
     */
    EClass REAL_INST = eINSTANCE.getRealInst();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.RMWImpl <em>RMW</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.RMWImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getRMW()
     * @generated
     */
    EClass RMW = eINSTANCE.getRMW();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RMW__SIZE = eINSTANCE.getRMW_Size();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.SMWImpl <em>SMW</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.SMWImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getSMW()
     * @generated
     */
    EClass SMW = eINSTANCE.getSMW();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SMW__VALUE = eINSTANCE.getSMW_Value();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.SMSImpl <em>SMS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.SMSImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getSMS()
     * @generated
     */
    EClass SMS = eINSTANCE.getSMS();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SMS__VALUE = eINSTANCE.getSMS_Value();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.PUSHImpl <em>PUSH</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.PUSHImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getPUSH()
     * @generated
     */
    EClass PUSH = eINSTANCE.getPUSH();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.POPImpl <em>POP</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.POPImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getPOP()
     * @generated
     */
    EClass POP = eINSTANCE.getPOP();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.LOADImpl <em>LOAD</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.LOADImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getLOAD()
     * @generated
     */
    EClass LOAD = eINSTANCE.getLOAD();

    /**
     * The meta object literal for the '<em><b>Reg</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOAD__REG = eINSTANCE.getLOAD_Reg();

    /**
     * The meta object literal for the '<em><b>Address</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOAD__ADDRESS = eINSTANCE.getLOAD_Address();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.RegisterImpl <em>Register</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.RegisterImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getRegister()
     * @generated
     */
    EClass REGISTER = eINSTANCE.getRegister();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REGISTER__NAME = eINSTANCE.getRegister_Name();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.ImmediateImpl <em>Immediate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.ImmediateImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getImmediate()
     * @generated
     */
    EClass IMMEDIATE = eINSTANCE.getImmediate();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMMEDIATE__VALUE = eINSTANCE.getImmediate_Value();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.ValueImpl <em>Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.ValueImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getValue()
     * @generated
     */
    EClass VALUE = eINSTANCE.getValue();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VALUE__LABEL = eINSTANCE.getValue_Label();

    /**
     * The meta object literal for the '<em><b>Num</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUE__NUM = eINSTANCE.getValue_Num();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.ConstImpl <em>Const</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.ConstImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getConst()
     * @generated
     */
    EClass CONST = eINSTANCE.getConst();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.HexConstImpl <em>Hex Const</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.HexConstImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getHexConst()
     * @generated
     */
    EClass HEX_CONST = eINSTANCE.getHexConst();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.DirectImpl <em>Direct</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.DirectImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getDirect()
     * @generated
     */
    EClass DIRECT = eINSTANCE.getDirect();

    /**
     * The meta object literal for the '<em><b>Address</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIRECT__ADDRESS = eINSTANCE.getDirect_Address();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.DirectRegImpl <em>Direct Reg</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.DirectRegImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getDirectReg()
     * @generated
     */
    EClass DIRECT_REG = eINSTANCE.getDirectReg();

    /**
     * The meta object literal for the '<em><b>Reg</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIRECT_REG__REG = eINSTANCE.getDirectReg_Reg();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.STOREImpl <em>STORE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.STOREImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getSTORE()
     * @generated
     */
    EClass STORE = eINSTANCE.getSTORE();

    /**
     * The meta object literal for the '<em><b>Reg</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORE__REG = eINSTANCE.getSTORE_Reg();

    /**
     * The meta object literal for the '<em><b>Address</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORE__ADDRESS = eINSTANCE.getSTORE_Address();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.AddressImpl <em>Address</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.AddressImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getAddress()
     * @generated
     */
    EClass ADDRESS = eINSTANCE.getAddress();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MOVEImpl <em>MOVE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MOVEImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getMOVE()
     * @generated
     */
    EClass MOVE = eINSTANCE.getMOVE();

    /**
     * The meta object literal for the '<em><b>Dst</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MOVE__DST = eINSTANCE.getMOVE_Dst();

    /**
     * The meta object literal for the '<em><b>Src</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MOVE__SRC = eINSTANCE.getMOVE_Src();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MoveValueImpl <em>Move Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MoveValueImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getMoveValue()
     * @generated
     */
    EClass MOVE_VALUE = eINSTANCE.getMoveValue();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.ADDImpl <em>ADD</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.ADDImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getADD()
     * @generated
     */
    EClass ADD = eINSTANCE.getADD();

    /**
     * The meta object literal for the '<em><b>Dst</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD__DST = eINSTANCE.getADD_Dst();

    /**
     * The meta object literal for the '<em><b>Src1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD__SRC1 = eINSTANCE.getADD_Src1();

    /**
     * The meta object literal for the '<em><b>Src2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD__SRC2 = eINSTANCE.getADD_Src2();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.SUBImpl <em>SUB</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.SUBImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getSUB()
     * @generated
     */
    EClass SUB = eINSTANCE.getSUB();

    /**
     * The meta object literal for the '<em><b>Dst</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUB__DST = eINSTANCE.getSUB_Dst();

    /**
     * The meta object literal for the '<em><b>Src1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUB__SRC1 = eINSTANCE.getSUB_Src1();

    /**
     * The meta object literal for the '<em><b>Src2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUB__SRC2 = eINSTANCE.getSUB_Src2();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.CMPImpl <em>CMP</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.CMPImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getCMP()
     * @generated
     */
    EClass CMP = eINSTANCE.getCMP();

    /**
     * The meta object literal for the '<em><b>Src1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMP__SRC1 = eINSTANCE.getCMP_Src1();

    /**
     * The meta object literal for the '<em><b>Src2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CMP__SRC2 = eINSTANCE.getCMP_Src2();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.BEQImpl <em>BEQ</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.BEQImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getBEQ()
     * @generated
     */
    EClass BEQ = eINSTANCE.getBEQ();

    /**
     * The meta object literal for the '<em><b>Dest</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BEQ__DEST = eINSTANCE.getBEQ_Dest();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.BranchAddressImpl <em>Branch Address</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.BranchAddressImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getBranchAddress()
     * @generated
     */
    EClass BRANCH_ADDRESS = eINSTANCE.getBranchAddress();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.BLTImpl <em>BLT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.BLTImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getBLT()
     * @generated
     */
    EClass BLT = eINSTANCE.getBLT();

    /**
     * The meta object literal for the '<em><b>Dest</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BLT__DEST = eINSTANCE.getBLT_Dest();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.BRANCHImpl <em>BRANCH</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.BRANCHImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getBRANCH()
     * @generated
     */
    EClass BRANCH = eINSTANCE.getBRANCH();

    /**
     * The meta object literal for the '<em><b>Dest</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BRANCH__DEST = eINSTANCE.getBRANCH_Dest();

    /**
     * The meta object literal for the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.BLINKImpl <em>BLINK</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.BLINKImpl
     * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.impl.MiniARMPackageImpl#getBLINK()
     * @generated
     */
    EClass BLINK = eINSTANCE.getBLINK();

    /**
     * The meta object literal for the '<em><b>Reg</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BLINK__REG = eINSTANCE.getBLINK_Reg();

    /**
     * The meta object literal for the '<em><b>Dest</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BLINK__DEST = eINSTANCE.getBLINK_Dest();

  }

} //MiniARMPackage
