/**
 * generated by Xtext 2.27.0
 */
package fr.centralesupelec.infonum.sl.miniarm.miniARM;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pseudo Inst</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.PseudoInst#getReg <em>Reg</em>}</li>
 * </ul>
 *
 * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.MiniARMPackage#getPseudoInst()
 * @model
 * @generated
 */
public interface PseudoInst extends Instruction
{
  /**
   * Returns the value of the '<em><b>Reg</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reg</em>' containment reference.
   * @see #setReg(Register)
   * @see fr.centralesupelec.infonum.sl.miniarm.miniARM.MiniARMPackage#getPseudoInst_Reg()
   * @model containment="true"
   * @generated
   */
  Register getReg();

  /**
   * Sets the value of the '{@link fr.centralesupelec.infonum.sl.miniarm.miniARM.PseudoInst#getReg <em>Reg</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reg</em>' containment reference.
   * @see #getReg()
   * @generated
   */
  void setReg(Register value);

} // PseudoInst
