/*
 * generated by Xtext 2.27.0
 */
package fr.centralesupelec.infonum.sl.miniarm.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.centralesupelec.infonum.sl.miniarm.MiniARMRuntimeModule;
import fr.centralesupelec.infonum.sl.miniarm.MiniARMStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MiniARMIdeSetup extends MiniARMStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MiniARMRuntimeModule(), new MiniARMIdeModule()));
	}
	
}
