/*
 * generated by Xtext 2.27.0
 */
package fr.centralesupelec.infonum.sl.miniarm;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MiniARMStandaloneSetup extends MiniARMStandaloneSetupGenerated {

	public static void doSetup() {
		new MiniARMStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
